[package]
name = "faer_gmres"
version = "0.1.0"
edition = "2021"

[lib]
name = "faer_gmres"
# dylib emits .so, rlib setting emits rust lib files
crate-type = ["cdylib", "rlib"]
path = 'src/lib.rs'

[dependencies]
assert_approx_eq = "*"
faer = {version = "0.18.2"}
